targets:
  $default:
    builders:
      json_serializable|json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
        generate_for:
          - "**/**.data.dart"
      freezed|freezed:
        generate_for:
          - "**/**.model.dart"
          - "**/**.data.dart"